kind: Service
apiVersion: v1
metadata:
  name: bookstoremanager-service
spec:
  selector:
    app: bookstoremanager
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-bookstoremanager
  labels:
    app: bookstoremanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstoremanager
  template:
    metadata:
      labels:
        app: bookstoremanager
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080